name: Pratik Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "23 6 * * *"
    - cron: "23 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.PRATIK_1576_TOKEN }}
          leetcode-session: ${{ secrets.PRATIK_1576_SESSION }}
          destination-folder: pratik_1576
